name: About Ahmed Othman
title: About Ahmed Othman
url: 'https://aothman.de'
baseurl: '' #change it according to your repository name
description: Ahmed is an Engineering Manager with 6+ years of Engineering Leadership experience, In love with people diversity and helping people grow and develop their skills.